# Atividade 2 — Exercícios de Limpeza, Transformação e Agrupamento de Dados

Responda as perguntas abaixo usando o dataset **emendas_tratamento.parquet**. o dataset pode ser baixado em https://drive.google.com/file/d/19ydA23-eboyiKxN29JL1EQWW4CplTiKg/view?usp=sharing.

Cada resposta deve ter:
- Uma célula de **código** com a solução
- Uma célula de **texto** (Markdown) com a sua interpretação do resultado

---
## Passo 0 — Importar pandas e carregar os dados

In [120]:
import pandas as pd 

dados = pd.read_parquet("https://drive.google.com/uc?export=download&id=19ydA23-eboyiKxN29JL1EQWW4CplTiKg")

display(dados)
dados.info()

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1
0,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,ALVORADA - RS,4300604,ALVORADA,4300000,...,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,700000.00,0.0,0.0,0.0,690900.00,9100.00,Sem informação
1,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,SANTA ISABEL DO PARÁ - PA,1506500,SANTA ISABEL DO PARÁ,1500000,...,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,487500.00,0.0,0.0,0.0,487500.00,0.00,Sem informação
2,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,BARRA BONITA - SC,4202099,BARRA BONITA,4200000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,100000.00,0.0,0.0,0.0,0.00,100000.00,Sem informação
3,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,ARARAQUARA - SP,3503208,ARARAQUARA,3500000,...,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,243750.00,0.0,0.0,0.0,243750.00,0.00,Sem informação
4,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,CAMPO LARGO - PR,4104204,CAMPO LARGO,4100000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,1658333.94,0.0,0.0,0.0,527200.00,1131133.94,Sem informação
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88654,201811420017,2018,Emenda Individual - Transferências com Finalid...,1142.0,ZE GERALDO,17,PARÁ (UF),Sem informação,Sem informação,1500000,...,CONSTRUCAO E AMPLIACAO DE UNIDADES OPERACIONAI...,EIND,EMENDA INDIVIDUAL,500000.00,0.0,0.0,0.0,369387.36,130612.64,201811420017
88655,201827690001,2018,Emenda Individual - Transferências com Finalid...,2769.0,ZE SILVA,1,MÚLTIPLO,Sem informação,Múltiplo,3100000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,EIND,EMENDA INDIVIDUAL,499975.00,499975.0,499975.0,0.0,0.00,0.00,201827690001
88656,201827690002,2018,Emenda Individual - Transferências com Finalid...,2769.0,ZE SILVA,2,ITURAMA - MG,3134400,ITURAMA,3100000,...,APOIO A PROJETOS DE DESENVOLVIMENTO SUSTENTAVE...,EIND,EMENDA INDIVIDUAL,200000.00,0.0,0.0,11058.0,0.00,188942.00,201827690002
88657,201827690003,2018,Emenda Individual - Transferências com Finalid...,2769.0,ZE SILVA,3,ITURAMA - MG,3134400,ITURAMA,3100000,...,ESTRUTURACAO DE UNIDADES DE ATENCAO ESPECIALIZ...,EIND,EMENDA INDIVIDUAL,199970.00,199970.0,199970.0,0.0,0.00,0.00,201827690003
88658,201827690004,2018,Emenda Individual - Transferências com Finalid...,2769.0,ZE SILVA,4,POUSO ALEGRE - MG,3152501,POUSO ALEGRE,3100000,...,APOIO A REALIZACAO DE EVENTOS DE ESPORTE AMADO...,EIND,EMENDA INDIVIDUAL,100000.00,0.0,0.0,0.0,6617.47,93382.53,201827690004

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88659 entries, 0 to 88658
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Código da Emenda                    88659 non-null  object
 1   Ano da Emenda                       88659 non-null  int64
 2   Tipo de Emenda                      88659 non-null  object
 3   Código do Autor da Emenda           72698 non-null  float64
 4   Nome do Autor da Emenda             72698 non-null  object
 5   Número da emenda                    88659 non-null  object
 6   Localidade de aplicação do recurso  88659 non-null  object
 7   Código Município IBGE               88659 non-null  object
 8   Município                           88659 non-null  object
 9   Código UF IBGE                      88659 non-null  int64
 10  UF                                  88659 non-null  object
 11  Região                              88659 non-null  object
 12  Código Função                       88659 non-null  object
 13  Nome Função                         88659 non-null  object
 14  Código Subfunção                    88659 non-null  object
 15  Nome Subfunção                      88659 non-null  object
 16  Código Programa                     88659 non-null  object
 17  Nome Programa                       88659 non-null  object
 18  Código Ação                         88659 non-null  object
 19  Nome Ação                           88659 non-null  object
 20  Código Plano Orçamentário           88659 non-null  object
 21  Nome Plano Orçamentário             88659 non-null  object
 22  Valor Empenhado                     88659 non-null  float64
 23  Valor Liquidado                     88659 non-null  float64
 24  Valor Pago                          88659 non-null  float64
 25  Valor Restos A Pagar Inscritos      88659 non-null  float64
 26  Valor Restos A Pagar Cancelados     88659 non-null  float64
 27  Valor Restos A Pagar Pagos          88659 non-null  float64
 28  Código da Emenda_1                  88659 non-null  object
dtypes: float64(7), int64(2), object(20)
memory usage: 19.6+ MB

## 1) Filtre apenas as emendas do ano de **2022** e mostre as 30 primeiras linhas. Em seguida responda: Quanta emendas foram registradas em 2022?

In [121]:
dados_2022 = dados[dados["Ano da Emenda"] == 2022]

display(dados_2022.head(30))
print(len(dados_2022))

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1
63473,202238950001,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,1,CONCEIÇÃO DO ALMEIDA - BA,2908309,CONCEIÇÃO DO ALMEIDA,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202238950001
63474,202238950002,2022,Emenda Individual - Transferências com Finalid...,3895.0,ABILIO SANTANA,2,CONCEIÇÃO DO ALMEIDA - BA,2908309,CONCEIÇÃO DO ALMEIDA,2900000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,750141.00,750141.00,750141.00,0.00,0.0,0.00,202238950002
63475,202238950003,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,3,CRUZ DAS ALMAS - BA,2909802,CRUZ DAS ALMAS,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202238950003
63476,202238950004,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,4,IRAMAIA - BA,2914307,IRAMAIA,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,200000.00,0.00,0.00,200000.00,0.0,200000.00,202238950004
63477,202238950005,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,5,MUCURI - BA,2922003,MUCURI,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202238950005
63478,202238950006,2022,Emenda Individual - Transferências com Finalid...,3895.0,ABILIO SANTANA,6,SERRA DO RAMALHO - BA,2930154,SERRA DO RAMALHO,2900000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,535815.00,535815.00,535815.00,0.00,0.0,0.00,202238950006
63479,202238950007,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,7,SOUTO SOARES - BA,2930808,SOUTO SOARES,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,200000.00,0.00,0.00,200000.00,0.0,200000.00,202238950007
63480,202238950008,2022,Emenda Individual - Transferências com Finalid...,3895.0,ABILIO SANTANA,8,MÚLTIPLO,Sem informação,Múltiplo,2900000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,470837.00,470837.00,470837.00,0.00,0.0,0.00,202238950008
63481,202238950009,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,9,MÚLTIPLO,Sem informação,Múltiplo,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,1100000.00,0.00,0.00,1100000.00,0.0,1100000.00,202238950009
63482,202238950010,2022,Emenda Individual - Transferências com Finalid...,3895.0,ABILIO SANTANA,10,MÚLTIPLO,Sem informação,Múltiplo,2900000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,8573048.00,8123048.00,8123048.00,450000.00,0.0,450000.00,202238950010
63483,202238950011,2022,Emenda Individual - Transferências Especiais,3895.0,ABILIO SANTANA,11,MÚLTIPLO,Sem informação,Múltiplo,2900000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,4000000.00,3500000.00,3500000.00,500000.00,0.0,500000.00,202238950011
63484,202238950012,2022,Emenda Individual - Transferências com Finalid...,3895.0,ABILIO SANTANA,12,BAHIA (UF),Sem informação,Sem informação,2900000,...,FORTALECIMENTO DO SISTEMA NACIONAL DE VIGILANC...,0,FORTALECIMENTO DO SISTEMA NACIONAL DE VIGILANC...,1071631.00,0.00,0.00,1071631.00,0.0,1071631.00,202238950012
63485,202238960001,2022,Emenda Individual - Transferências com Finalid...,3896.0,ABOU ANNI,1,SÃO PAULO (UF),Sem informação,Sem informação,3500000,...,ESTRUTURACAO DE UNIDADES DE ATENCAO ESPECIALIZ...,0,ESTRUTURACAO DE UNIDADES DE ATENCAO ESPECIALIZ...,811695.00,99962.00,99962.00,711733.00,711733.0,0.00,202238960001
63486,202238960002,2022,Emenda Individual - Transferências Especiais,3896.0,ABOU ANNI,2,MÚLTIPLO,Sem informação,Múltiplo,3500000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,8800000.00,4400000.00,4400000.00,4400000.00,0.0,4400000.00,202238960002
63487,202238960003,2022,Emenda Individual - Transferências com Finalid...,3896.0,ABOU ANNI,3,MÚLTIPLO,Sem informação,Múltiplo,3500000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,6517305.00,6517305.00,6517305.00,0.00,0.0,0.00,202238960003
63488,202238960004,2022,Emenda Individual - Transferências com Finalid...,3896.0,ABOU ANNI,4,MÚLTIPLO,Sem informação,Múltiplo,3500000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,2172435.00,2172435.00,2172435.00,0.00,0.0,0.00,202238960004
63489,202238970001,2022,Emenda Individual - Transferências Especiais,3897.0,ACACIO FAVACHO,1,MÚLTIPLO,Sem informação,Múltiplo,1600000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,8819682.00,4409841.00,4409841.00,4409841.00,0.0,4409841.00,202238970001
63490,202238970002,2022,Emenda Individual - Transferências com Finalid...,3897.0,ACACIO FAVACHO,2,MÚLTIPLO,Sem informação,Múltiplo,1600000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,5432050.00,5432050.00,5432050.00,0.00,0.0,0.00,202238970002
63491,202238970003,2022,Emenda Individual - Transferências com Finalid...,3897.0,ACACIO FAVACHO,3,AMAPÁ (UF),Sem informação,Sem informação,1600000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,4149741.00,4149741.00,4149741.00,0.00,0.0,0.00,202238970003
63492,202226330001,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,1,Nacional,Sem informação,Sem informação,-1,...,APRESTAMENTO DAS FORCAS - MANUTENCAO DA PRONTI...,0,APRESTAMENTO DAS FORCAS - MANUTENCAO DA PRONTI...,249999.67,240235.01,204095.01,45904.66,0.0,45904.66,202226330001
63493,202226330002,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,2,Nacional,Sem informação,Sem informação,-1,...,ASSISTENCIA MEDICA QUALIFICADA E GRATUITA A TO...,0,ASSISTENCIA MEDICA QUALIFICADA E GRATUITA A TO...,108641.00,108641.00,108641.00,0.00,0.0,0.00,202226330002
63494,202226330003,2022,Emenda Individual - Transferências Especiais,2633.0,ACIR GURGACZ,3,CABIXI - RO,1100031,CABIXI,1100000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,350000.00,0.00,0.00,350000.00,0.0,350000.00,202226330003
63495,202226330004,2022,Emenda Individual - Transferências Especiais,2633.0,ACIR GURGACZ,4,JI-PARANÁ - RO,1100122,JI-PARANÁ,1100000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202226330004
63496,202226330005,2022,Emenda Individual - Transferências Especiais,2633.0,ACIR GURGACZ,5,SÃO FELIPE D'OESTE - RO,1101484,SÃO FELIPE D'OESTE,1100000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202226330005
63497,202226330006,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,6,MÚLTIPLO,Sem informação,Múltiplo,-14,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,3280613.00,3080613.00,3080613.00,200000.00,0.0,200000.00,202226330006
63498,202226330007,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,7,SÃO PAULO (UF),Sem informação,Sem informação,3500000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,543205.00,543205.00,543205.00,0.00,0.0,0.00,202226330007
63499,202226330008,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,8,MÚLTIPLO,Sem informação,Múltiplo,1100000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,3041948.00,2791948.00,2791948.00,250000.00,0.0,250000.00,202226330008
63500,202226330009,2022,Emenda Individual - Transferências com Finalid...,2633.0,ACIR GURGACZ,9,CURITIBA - PR,4106902,CURITIBA,4100000,...,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,651846.00,651846.00,651846.00,0.00,0.0,0.00,202226330009
63501,202226330010,2022,Emenda Individual - Transferências Especiais,2633.0,ACIR GURGACZ,10,ARIQUEMES - RO,1100023,ARIQUEMES,1100000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,500000.00,0.00,0.00,500000.00,0.0,500000.00,202226330010
63502,202226330011,2022,Emenda Individual - Transferências Especiais,2633.0,ACIR GURGACZ,11,ALTA FLORESTA D'OESTE - RO,1100015,ALTA FLORESTA D'OESTE,1100000,...,TRANSFERENCIAS ESPECIAIS,0,TRANSFERENCIAS ESPECIAIS,250000.00,0.00,0.00,250000.00,0.0,250000.00,202226330011

6108

Foram registradas 6108 emendas no ano de 2022

## 2) Filtre as emendas da região **Norte** que tenham `Valor Empenhado` maior que **500.000** e mostre as 5 primeiras linhas. Em seguida, responda: quantas emendas atendem a esses duas condições ao mesmo tempo?

In [122]:
display(dados["Região"].unique().tolist())
dados_norte_rico = dados[(dados["Região"] == "Norte") & (dados["Valor Empenhado"] > 500000)]

display(dados_norte_rico.head())
print(len(dados_norte_rico))

['Sul',
 'Norte',
 'Sudeste',
 'Nordeste',
 'Centro-Oeste',
 'Nacional',
 'Múltiplo',
 'Exterior']

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1
18,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,MÂNCIO LIMA - AC,1200336,MÂNCIO LIMA,1200000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,616610.0,0.0,0.0,0.0,0.0,616610.0,Sem informação
120,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,VITÓRIA DO JARI - AP,1600808,VITÓRIA DO JARI,1600000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,522384.4,0.0,0.0,0.0,0.0,522384.4,Sem informação
160,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,SANTANA - AP,1600600,SANTANA,1600000,...,IMPLEMENTACAO DE INFRAESTRUTURA BASICA NOS MUN...,0,IMPLEMENTACAO DE INFRAESTRUTURA BASICA NOS MUN...,4443000.0,0.0,0.0,0.0,4443000.0,0.0,Sem informação
170,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,PALMEIRAS DO TOCANTINS - TO,1713809,PALMEIRAS DO TOCANTINS,1700000,...,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,935350.0,0.0,0.0,0.0,0.0,935350.0,Sem informação
218,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,COSTA MARQUES - RO,1100080,COSTA MARQUES,1100000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,549995.0,0.0,0.0,0.0,159996.0,389999.0,Sem informação

6230

Há 6230 emendas do norte com valor superior a 500 mil

## 3) Filtre as emendas que são do estado de **SÃO PAULO** ou do estado do **RIO DE JANEIRO** e mostre quantas linhas cada estado possui. Em seguida, responda: Qual dos dois estados possui mais emendas e quantas são?

In [123]:
display(dados["Município"].unique().tolist())
dados_sp_rj = dados[(dados["Município"] == "SÃO PAULO") | (dados["Município"] == "RIO DE JANEIRO")]
display(dados_sp_rj.head())
print(f"sp:{len(dados[dados["Município"] == "SÃO PAULO"])}")
print(f"rj:{len(dados[dados["Município"] == "RIO DE JANEIRO"])}")

['ALVORADA',
 'SANTA ISABEL DO PARÁ',
 'BARRA BONITA',
 'ARARAQUARA',
 'CAMPO LARGO',
 'CAMPINAS DO SUL',
 'MORENO',
 'NOVA FLORESTA',
 'SANTIAGO DO SUL',
 'CIANORTE',
 'IPORÁ',
 'BRUMADO',
 'GUARAMIRANGA',
 'CRUZÍLIA',
 'SÃO MATEUS DO MARANHÃO',
 'SÃO GONÇALO DO AMARANTE',
 'ITALVA',
 'RIACHÃO DO JACUÍPE',
 'MÂNCIO LIMA',
 'PORTO MURTINHO',
 'PILAR DO SUL',
 'AMONTADA',
 'COMODORO',
 'SOBRADINHO',
 'BOM JESUS',
 'MONTE BELO DO SUL',
 'CABO DE SANTO AGOSTINHO',
 'PICUÍ',
 'ITAPECURU MIRIM',
 'IBIRAPUITÃ',
 'VALENÇA',
 'PORTO WALTER',
 'CASTANHAL',
 'SANTO ANTÔNIO DO PALMA',
 'APUCARANA',
 'FELIXLÂNDIA',
 'LENÇÓIS',
 'MONTE ALTO',
 'FERNANDO FALCÃO',
 'RUBIATABA',
 'FRANCISCO SANTOS',
 'REDENÇÃO',
 'SÃO FERNANDO',
 'RIO DAS OSTRAS',
 'MARCAÇÃO',
 'SÃO MIGUEL DOS CAMPOS',
 'CASTRO',
 'CANITAR',
 'SÍTIO DO MATO',
 'CÓRREGO NOVO',
 'Sem informação',
 'RIO MARIA',
 'ENTRE RIOS DE MINAS',
 'ALFREDO CHAVES',
 'OLÍMPIA',
 'NOSSA SENHORA DO SOCORRO',
 'CORIBE',
 'PALMITAL',
 'SANANDUVA',
 'BERTOLÍNIA',
 'MARACANAÚ',
 'MORRO REDONDO',
 'FARROUPILHA',
 'OURO PRETO',
 'SERRA NEGRA',
 'ALTAMIRA DO PARANÁ',
 'INÚBIA PAULISTA',
 'CAXIAS',
 'PAULISTA',
 'ITAMBÉ',
 'RIBEIRÃO VERMELHO',
 'IVOLÂNDIA',
 'BARRA DO MENDES',
 'VERA CRUZ',
 'ALTO DO RODRIGUES',
 'BRITÂNIA',
 'CHAPADA DO NORTE',
 'BARRA VELHA',
 'BANDEIRA DO SUL',
 'ARAÚJOS',
 'MUNDO NOVO',
 'ITAÍBA',
 'ANDARAÍ',
 'NOVAIS',
 'ITUPIRANGA',
 'ORÓS',
 'TUPANCIRETÃ',
 'BARRA DO PIRAÍ',
 'CAMAMU',
 'CONDADO',
 'NOVO ORIENTE',
 'AURELINO LEAL',
 'SEM-PEIXE',
 'NOVO HORIZONTE',
 'EUNÁPOLIS',
 'JARAGUARI',
 'GUAÍRA',
 'SANTA FÉ',
 'SAPÉ',
 'CHÃ GRANDE',
 'SOROCABA',
 'MARAJÁ DO SENA',
 'ATALAIA',
 'MARUIM',
 'PIRACEMA',
 'LÁBREA',
 'GARUVA',
 'KALORÉ',
 'CARMO',
 'BARRINHA',
 'MAUÁ',
 'SIDROLÂNDIA',
 'ALTO ALEGRE DOS PARECIS',
 'OCARA',
 'DORES DO TURVO',
 'AÇU',
 'VIÇOSA DO CEARÁ',
 'VITÓRIA DO JARI',
 'BOM JESUS DA LAPA',
 'PATY DO ALFERES',
 'GURINHATÃ',
 'SERAFINA CORRÊA',
 'FORMOSO',
 'VISTA SERRANA',
 'SÃO MATEUS DO SUL',
 'OLINDA NOVA DO MARANHÃO',
 'NOVO LINO',
 'ALMADINA',
 'ULIANÓPOLIS',
 'ARAGUANÃ',
 'ERVÁLIA',
 'LIMA DUARTE',
 'BRUNÓPOLIS',
 'CAJAZEIRAS DO PIAUÍ',
 'IVAIPORÃ',
 'DIVINO',
 'SUZANO',
 'OLIVEIRA DOS BREJINHOS',
 'AVAÍ',
 "MÃE D'ÁGUA",
 'MATHIAS LOBATO',
 'CAPÃO DO CIPÓ',
 'SANTO EXPEDITO',
 'FEIJÓ',
 'FRECHEIRINHA',
 'SÃO MIGUEL DO IGUAÇU',
 'VILA MARIA',
 'PIÊN',
 'PIRAPOZINHO',
 'VICENTINA',
 'CANOINHAS',
 'PUREZA',
 'SANTANA',
 'SÃO PEDRO',
 'SÃO DOMINGOS',
 'CURVELO',
 'PORTO SEGURO',
 'PANTANO GRANDE',
 'LAPA',
 'SANTA LUZIA',
 'SANTA MARIA DO OESTE',
 'PALMEIRAS DO TOCANTINS',
 'NOVA OLINDA',
 'SERRANA',
 'SÃO JORGE DO PATROCÍNIO',
 'CAIÇARA DO RIO DO VENTO',
 'RAUL SOARES',
 'CENTRAL',
 'SANTA RITA DE CALDAS',
 'CUIABÁ',
 'CONCEIÇÃO DA BARRA',
 'VILHENA',
 'ABAÍRA',
 'AMÉRICO DE CAMPOS',
 'JANDAIA',
 'QUEIROZ',
 'ALTEROSA',
 'JUIZ DE FORA',
 'IPANGUAÇU',
 'IRAQUARA',
 'JATAÚBA',
 'PIRIPIRI',
 'PASSA-VINTE',
 'SANTA MARIA DAS BARREIRAS',
 'SÃO JOSÉ DO INHACORÁ',
 'ITAGUAÇU',
 'EMBU',
 'AMPARO',
 'JARDIM ALEGRE',
 'SANTA ROSA DO PURUS',
 'ITANHAÉM',
 'SABARÁ',
 'POÇO DE JOSÉ DE MOURA',
 'GALVÃO',
 'CARAPICUÍBA',
 'ALTOS',
 'NOVA IGUAÇU',
 'JAURU',
 'PIRAÚBA',
 'MARÍLIA',
 'SALOÁ',
 'ÁGUA DOCE DO NORTE',
 'GUAJERU',
 'MARCO',
 'NOVA EUROPA',
 'COSTA MARQUES',
 'PEJUÇARA',
 'SÃO VALÉRIO DO SUL',
 'BELA VISTA DE GOIÁS',
 'GRAMADO',
 'FLORESTA DO PIAUÍ',
 'DIANÓPOLIS',
 'CAETÉ',
 'TOMAR DO GERU',
 'BELA CRUZ',
 'SANTO ANTÔNIO DA PATRULHA',
 'CAMETÁ',
 'MOITA BONITA',
 'VITOR MEIRELES',
 'RIO DO SUL',
 'FLORES DA CUNHA',
 'WANDERLÂNDIA',
 'TOBIAS BARRETO',
 'ELDORADO',
 'LARANJAL',
 'CURITIBANOS',
 'PORTO ALEGRE',
 'NOVA CANAÃ',
 'PRATÂNIA',
 'TOCANTINÓPOLIS',
 'MENDES',
 'CABO VERDE',
 'SÃO GONÇALO',
 'CACHOEIRAS DE MACACU',
 'XAPURI',
 'PINDORETAMA',
 'CONCEIÇÃO DA APARECIDA',
 'SANTANA DO ITARARÉ',
 'PRAIA GRANDE',
 'BIRITIBA-MIRIM',
 'LAVANDEIRA',
 'PARNAÍBA',
 'LAGAMAR',
 'CLÁUDIA',
 'SÃO BENTO DO SUL',
 'PEDRA BRANCA',
 'BOMBINHAS',
 'BARRO ALTO',
 'JUATUBA',
 'MONTEIRO',
 'COLORADO DO OESTE',
 'CALUMBI',
 'GUARIBA',
 'ITAMBARACÁ',
 'TUPARENDI',
 'DELTA',
 'SANTA GERTRUDES',
 'ICAPUÍ',
 'SÃO CARLOS',
 'BELÉM DO SÃO FRANCISCO',
 'RIO BRANCO',
 'SANTO ANTÔNIO DO JARDIM',
 'GOVERNADOR VALADARES',
 'SÃO FRANCISCO DO PARÁ',
 'RIBEIRÃO CORRENTE',
 'PIRENÓPOLIS',
 'BARRA FUNDA',
 'ENTRE-IJUÍS',
 'JARU',
 'ERECHIM',
 'TAPERA',
 'IELMO MARINHO',
 'GUAIMBÊ',
 'SANTO ANTÔNIO DE PÁDUA',
 'TABULEIRO',
 'MURITIBA',
 'ALTO PARAGUAI',
 'CAÇAPAVA DO SUL',
 'GOVERNADOR DIX-SEPT ROSADO',
 'MORRINHOS',
 'ARACAJU',
 'ÁGUA FRIA',
 'TUFILÂNDIA',
 'RIO GRANDE',
 'JOSELÂNDIA',
 'RIO PARDO',
 'LAGO VERDE',
 'LUZIÂNIA',
 'NITERÓI',
 'RIO PRETO',
 'LONTRAS',
 'HUMAITÁ',
 'PARACATU',
 'INHUMAS',
 'FRUTUOSO GOMES',
 'ARCOVERDE',
 'SAPIRANGA',
 'ARAPOTI',
 'PINDAMONHANGABA',
 'GUARAÇAÍ',
 'SÃO JOSÉ DA VARGINHA',
 'CORNÉLIO PROCÓPIO',
 'ITAPETIM',
 'ALAGOA NOVA',
 'MACATUBA',
 'ITAÚNA',
 'ARROIO DO TIGRE',
 'BOCAIÚVA',
 'ENCRUZILHADA DO SUL',
 'SANTA TERESA',
 'ITAITUBA',
 'PIÚMA',
 'INHAPIM',
 'ICARAÍMA',
 'CRUZ',
 'SANTO ANTÔNIO DO AMPARO',
 'CURRAL DE DENTRO',
 'PALESTINA DO PARÁ',
 'SÃO PAULO',
 'PIRAQUARA',
 'PELOTAS',
 'TIRADENTES DO SUL',
 'CANTAGALO',
 'FERNANDO PRESTES',
 'TAQUARITINGA',
 'VALE DO PARAÍSO',
 'FELIPE GUERRA',
 'SANTO ANTÔNIO DO MONTE',
 'GUARABIRA',
 'BOFETE',
 'JANAÚBA',
 'PORTO VELHO',
 'CABRÁLIA PAULISTA',
 'SÃO JOAQUIM DO MONTE',
 'BARROSO',
 'LUIZIÂNIA',
 'RIBEIRÃO GRANDE',
 'BOA VISTA DO INCRA',
 'CONGONHAS',
 'ARAUCÁRIA',
 'VARGEM BONITA',
 'SANTA LUZIA DO ITANHY',
 'INDEPENDÊNCIA',
 'NILÓPOLIS',
 'FAZENDA RIO GRANDE',
 'SANCLERLÂNDIA',
 'RIO REAL',
 'ITAMARANDIBA',
 'RIO DAS ANTAS',
 'CORDEIRO',
 'SÃO JOSÉ DO VALE DO RIO PRETO',
 'JUQUIÁ',
 'IRATI',
 'PALMAS',
 'PALMEIRÂNDIA',
 'CONTAGEM',
 'SERRA DO MEL',
 'PONTE ALTA DO BOM JESUS',
 'ABEL FIGUEIREDO',
 'FRANCA',
 'TAUÁ',
 'SÃO PEDRO DE ALCÂNTARA',
 'ITACARAMBI',
 'LIMOEIRO DO NORTE',
 'ÁGUAS DE CHAPECÓ',
 'ARAGOMINAS',
 'ITAPAGÉ',
 'TANQUINHO',
 'LAGOA DO SÍTIO',
 'SANTA ROSA DE GOIÁS',
 'SANTA ISABEL',
 'ITAPIPOCA',
 'SANTANA DO LIVRAMENTO',
 'PARAOPEBA',
 'CRUZ DAS ALMAS',
 'GUARAPUAVA',
 'IJUÍ',
 'PORANGATU',
 'LEOPOLDINA',
 'DAMIÃO',
 'COLMÉIA',
 'IGUARACI',
 'CORINTO',
 'PACAJÁ',
 'SÃO TOMÁS DE AQUINO',
 'FEIRA DE SANTANA',
 'CAPELA DE SANTANA',
 'HIDROLÂNDIA',
 'DRACENA',
 'URUARÁ',
 'QUIXERÉ',
 'ARINOS',
 'FRANCISCO DANTAS',
 'SÃO JOSÉ DO SERIDÓ',
 'CARACARAÍ',
 'CATANDUVAS',
 'PARNAGUÁ',
 'CONCEIÇÃO DO ALMEIDA',
 'CAMARAGIBE',
 'CANÁPOLIS',
 'NOVA LONDRINA',
 'ANGELIM',
 'SANTA RITA DO PARDO',
 'JAGUARIÚNA',
 'COREAÚ',
 'COCAL DE TELHA',
 'CRUZALTENSE',
 'PORTO DOS GAÚCHOS',
 'SÃO MARCOS',
 'TURMALINA',
 'MINEIROS',
 'ANDIRÁ',
 'LAGARTO',
 'BARÃO DE GRAJAÚ',
 'GENERAL SALGADO',
 'NATAL',
 'PIRACURUCA',
 'ARMAÇÃO DOS BÚZIOS',
 'XAVANTINA',
 'VIÇOSA',
 'GUARACI',
 'RIO TINTO',
 'ALCINÓPOLIS',
 'INDAIAL',
 'FEIRA DA MATA',
 'SALTINHO',
 'ITUPEVA',
 'GUIA LOPES DA LAGUNA',
 'TAPIRAMUTÁ',
 'NOVA GUATAPORANGA',
 'SÃO JOÃO DO ITAPERIÚ',
 'NOVA CANAÃ DO NORTE',
 'IVOTI',
 'VALENTIM GENTIL',
 'MENDONÇA',
 'CAMPO VERDE',
 'MARINGÁ',
 'NÃO-ME-TOQUE',
 'MARCELINO RAMOS',
 'POÇO DANTAS',
 'CURAÇÁ',
 'MONTE APRAZÍVEL',
 'SÃO CAETANO DO SUL',
 'JENIPAPO DOS VIEIRAS',
 'CARVALHOS',
 'MASSARANDUBA',
 'PARAÚNA',
 "DIAMANTE D'OESTE",
 'ITAÚNA DO SUL',
 'TERRA DE AREIA',
 'PARAÚ',
 'SÃO JOÃO DO OESTE',
 'PEDRALVA',
 'RESPLENDOR',
 'PASSO DE TORRES',
 'POXORÉO',
 'TORRES',
 'SERTÃOZINHO',
 'ALEXANDRIA',
 'MARECHAL THAUMATURGO',
 'CAMBÉ',
 'FLORESTA DO ARAGUAIA',
 'ARACITABA',
 'JANDIRA',
 'VARGEM GRANDE PAULISTA',
 'SÃO JOÃO DE MERITI',
 'PADRE BERNARDO',
 'PIMENTEIRAS',
 'JARAGUÁ DO SUL',
 'GOVERNADOR LUIZ ROCHA',
 'COXIM',
 'RIO BRILHANTE',
 'JOAQUIM TÁVORA',
 'PINDAÍ',
 'BENTO GONÇALVES',
 'MOGI MIRIM',
 'SÃO MIGUEL DO GUAPORÉ',
 'SÃO PEDRO DO PIAUÍ',
 'CRISTALÂNDIA',
 'RODRIGUES ALVES',
 'PÃO DE AÇÚCAR',
 'NOVA PRATA DO IGUAÇU',
 'TUPÃ',
 'ABDON BATISTA',
 'TRÊS MARIAS',
 'PORTO XAVIER',
 'MAURILÂNDIA DO TOCANTINS',
 'PITANGA',
 'JUAZEIRO DO PIAUÍ',
 'SANTO ANTÔNIO DOS LOPES',
 'PORTALEGRE',
 'CACHOEIRA DO PIRIÁ',
 'CACIMBA DE DENTRO',
 'TIJUCAS',
 'POMPÉIA',
 'ARAXÁ',
 'SILVA JARDIM',
 'ITARUMÃ',
 'SÃO JOÃO DO CARIRI',
 'PAULO DE FARIA',
 'GUARUJÁ',
 'CAJATI',
 'AVEIRO',
 'OLIVEIRA',
 'BELA VISTA',
 'PARECIS',
 'MIRAÍMA',
 'DELMIRO GOUVEIA',
 'MISSAL',
 'RIANÁPOLIS',
 'ALTO RIO NOVO',
 'URUBICI',
 'MIRABELA',
 'ARARUNA',
 'ROCHEDO',
 'GARRUCHOS',
 'SATUBA',
 'SANTA LUZIA DO PARÁ',
 'PORTO NACIONAL',
 'VARZEDO',
 'ITAUBAL',
 'BAIXO GUANDU',
 'PEDRO DE TOLEDO',
 'SERINGUEIRAS',
 'OURICURI',
 'ORLÂNDIA',
 'AGUDO',
 'SÃO FRANCISCO',
 'TEIXEIRAS',
 'VERMELHO NOVO',
 'RIALMA',
 'LIDIANÓPOLIS',
 'BREJO',
 'GUARULHOS',
 'ITUVERAVA',
 'CABECEIRAS DO PIAUÍ',
 'RIACHO DAS ALMAS',
 'IGARAPÉ DO MEIO',
 'CARUARU',
 'MARCIONÍLIO SOUZA',
 'TEIXEIRA SOARES',
 'VÁRZEA PAULISTA',
 'PAROBÉ',
 'NEÓPOLIS',
 'NIQUELÂNDIA',
 'NOVA MÓDICA',
 'BARRETOS',
 'VERÊ',
 'SANTA CRUZ DOS MILAGRES',
 'CASTANHEIRA',
 'CANELINHA',
 'ITAJAÍ',
 'RIO GRANDE DO PIAUÍ',
 'AXIXÁ',
 'BARRA DO TURVO',
 'GUAREÍ',
 'RUSSAS',
 'SANTA ISABEL DO IVAÍ',
 'CRATEÚS',
 'ARAÇOIABA',
 'AURORA DO TOCANTINS',
 'MARILENA',
 'ESPERANTINA',
 'GUAPIARA',
 'PANELAS',
 'PONTA GROSSA',
 'CAMPO LARGO DO PIAUÍ',
 'OROCÓ',
 'ARROIO TRINTA',
 'VISTA ALEGRE',
 'SALINAS',
 'BEBERIBE',
 'MARIALVA',
 'CAETITÉ',
 'MACEDÔNIA',
 'ARAÇUAÍ',
 'MAXIMILIANO DE ALMEIDA',
 'LAJE DO MURIAÉ',
 'TURVÂNIA',
 'CONSELHEIRO LAFAIETE',
 'NOVA RESENDE',
 'AMÉRICA DOURADA',
 'PILAR',
 'SANTA CRUZ DO CAPIBARIBE',
 'ARRAIAS',
 'MATELÂNDIA',
 'CONCEIÇÃO DE MACABU',
 'SENA MADUREIRA',
 'DEPUTADO IRAPUAN PINHEIRO',
 'BANDEIRANTE',
 'MAIRIPORÃ',
 'BARRA DE SÃO MIGUEL',
 'CONCEIÇÃO DO CASTELO',
 'QUATIGUÁ',
 'SIMOLÂNDIA',
 'SÃO SEBASTIÃO DO UATUMÃ',
 'CAPÃO ALTO',
 'GLAUCILÂNDIA',
 'ABRE CAMPO',
 'JACARAÚ',
 'CAIEIRAS',
 'MILTON BRANDÃO',
 'SANTA MARIA DA SERRA',
 'JESUÍTAS',
 'MONTENEGRO',
 'IPABA',
 'CAFELÂNDIA',
 'BEQUIMÃO',
 'VÁRZEA',
 'FLORES DO PIAUÍ',
 'VILA NOVA DOS MARTÍRIOS',
 'PARANAÍBA',
 'JUNDIÁ',
 'SANTA QUITÉRIA DO MARANHÃO',
 'NOVA ESPERANÇA DO SUL',
 'CHAPECÓ',
 'JURUTI',
 'CAMPESTRE DO MARANHÃO',
 'PACOTI',
 'PINHAL',
 'ABREU E LIMA',
 'GUANAMBI',
 'ROSÁRIO DO IVAÍ',
 'TERRA RICA',
 "OLHO D'ÁGUA DAS CUNHÃS",
 'SÃO JOÃO DO MANHUAÇU',
 'MACAPARANA',
 'POMPÉU',
 'SÃO PEDRO DO BUTIÁ',
 'FLÓRIDA',
 'ACARAPE',
 'CARBONITA',
 'ITAPEBI',
 'CANTÁ',
 'FONTOURA XAVIER',
 'SUD MENNUCCI',
 'PERDIGÃO',
 'JOÃO PINHEIRO',
 'HONÓRIO SERPA',
 'ESTAÇÃO',
 'URUAÇU',
 'PÉROLA',
 'SÃO SEBASTIÃO DE LAGOA DE ROÇA',
 'PORTO ACRE',
 'IRECÊ',
 'SÃO BENTO',
 'TAIPU',
 'CACHOEIRINHA',
 'BANZAÊ',
 'GUAPÓ',
 'CRUZEIRO DO SUL',
 'ELDORADO DOS CARAJÁS',
 'AGRESTINA',
 'GAVIÃO',
 'SÃO JOÃO DA BOA VISTA',
 'ITAQUI',
 'TOMBOS',
 'PRESIDENTE TANCREDO NEVES',
 'MIRANDA DO NORTE',
 'SÃO JOÃO DO SOTER',
 'PARANATINGA',
 'INGAZEIRA',
 'COLINAS DO TOCANTINS',
 'RELVADO',
 'DAVID CANABARRO',
 'CÂNDIDO MOTA',
 'PORECATU',
 'CAPANEMA',
 'FAZENDA NOVA',
 'MULUNGU',
 'GRAVATAÍ',
 'MIRASSOL',
 'ARARAS',
 'SERRA DOURADA',
 'AFONSO CLÁUDIO',
 'PASSA SETE',
 'JUMIRIM',
 'ÁGUA NOVA',
 'MUZAMBINHO',
 'ITUMBIARA',
 'SÃO DOMINGOS DO ARAGUAIA',
 'UBAÍRA',
 'NOVO SANTO ANTÔNIO',
 'SÃO JOSÉ DO RIO CLARO',
 'MAFRA',
 'MARUMBI',
 'QUATRO PONTES',
 'CHAPADÃO DO CÉU',
 'MUCURI',
 'CATUÍPE',
 'BACABAL',
 'CAAPORÃ',
 'BURITIRANA',
 'LAJEADO',
 'ILHA GRANDE',
 'CORUMBATAÍ DO SUL',
 'PLANALTO',
 'MARAGOGI',
 'GUAIÚBA',
 'DOURADOS',
 'DOM ELISEU',
 'RIACHUELO',
 'PARANACITY',
 'SANTO ANTÔNIO DE POSSE',
 'RIO DO ANTÔNIO',
 'ACEGUÁ',
 'SÃO JOSÉ DO HORTÊNCIO',
 'DOM AQUINO',
 'ERMO',
 'CAMOCIM',
 'MIRIM DOCE',
 'IGAPORÃ',
 'ÁLVARES MACHADO',
 'TRÊS RIOS',
 'ENTRE RIOS',
 'CATUNDA',
 'RIO DO PIRES',
 'BARROS CASSAL',
 'MIMOSO DE GOIÁS',
 'MACHADINHO',
 'DOM PEDRO DE ALCÂNTARA',
 'BLUMENAU',
 'SANTO ANTÔNIO DO JACINTO',
 'CAMPINA VERDE',
 'IBIÚNA',
 'BARREIROS',
 'FLORIANÓPOLIS',
 'ARCOS',
 'FAXINAL DO SOTURNO',
 'FIRMINÓPOLIS',
 'OURO BRANCO',
 'SANTO ÂNGELO',
 'QUIXELÔ',
 'CRISÓLITA',
 'PRIMAVERA DE RONDÔNIA',
 'CARLOS BARBOSA',
 'MUNIZ FREIRE',
 'ATIBAIA',
 'CAPIVARI',
 'LARANJAL PAULISTA',
 'MATRINCHÃ',
 'MIRA ESTRELA',
 'PRESIDENTE PRUDENTE',
 'SÃO CARLOS DO IVAÍ',
 'PIRIPÁ',
 'PATOS DO PIAUÍ',
 'GOIATUBA',
 'RIO DO OESTE',
 "PINGO-D'ÁGUA",
 'DOIS IRMÃOS DAS MISSÕES',
 'BRAGANÇA',
 'NOVO XINGU',
 'BURITAMA',
 'CAATIBA',
 'NOVA IPIXUNA',
 'PIRAQUÊ',
 'GOVERNADOR JORGE TEIXEIRA',
 'RIO FORTUNA',
 'PENÁPOLIS',
 'TERESÓPOLIS',
 'CAMPINAS',
 'PANAMBI',
 'TIROS',
 'BARRA DO ROCHA',
 'NOVO ORIENTE DE MINAS',
 'TUPACIGUARA',
 'GAROPABA',
 'GUARANI DE GOIÁS',
 'DIVINOLÂNDIA DE MINAS',
 'IBIÁ',
 'ÁGUAS LINDAS DE GOIÁS',
 'SAPUCAIA',
 'BALNEÁRIO RINCÃO',
 'ALTO HORIZONTE',
 'TIBAU DO SUL',
 'BORACÉIA',
 'IBICARAÍ',
 'GUARARAPES',
 'SÃO JOSÉ DO SABUGI',
 'ELÓI MENDES',
 'BRASILÂNDIA DO TOCANTINS',
 'IPECAETÁ',
 'PORTO GRANDE',
 'BEBEDOURO',
 'RODEIO',
 'POÇO DAS ANTAS',
 'BURITIZEIRO',
 'OURIZONA',
 'PENEDO',
 'FARO',
 'GANDU',
 'RIO NEGRINHO',
 'TERRA ROXA',
 'CURIÚVA',
 'BALSAS',
 'FORMOSA DA SERRA NEGRA',
 'LUZERNA',
 'ARAPUÃ',
 'SÃO JOSÉ DO MANTIMENTO',
 'DIRCEU ARCOVERDE',
 'INDIAROBA',
 'ANGÉLICA',
 'NOVA ALVORADA',
 "SÃO JORGE D'OESTE",
 'SÃO PEDRO DA ALDEIA',
 'IGUATU',
 'GUARIBAS',
 'SÃO FRANCISCO DE ASSIS DO PIAUÍ',
 'NOVA UNIÃO',
 'TAPIRA',
 'GOVERNADOR EUGÊNIO BARROS',
 'SENADOR CANEDO',
 'SANTANÓPOLIS',
 'LAGO DA PEDRA',
 'AMÉRICO BRASILIENSE',
 'ADUSTINA',
 'LAGOA DE VELHOS',
 'IGUATEMI',
 'RIO VERDE DE MATO GROSSO',
 'GUARATINGUETÁ',
 'ARUANÃ',
 'RIO BRANCO DO IVAÍ',
 'ITARARÉ',
 'SÃO VICENTE',
 'CORUMBÁ',
 'JABOATÃO DOS GUARARAPES',
 'PUTINGA',
 'TOUROS',
 'ITAPUÃ DO OESTE',
 'LIVRAMENTO',
 'CAXAMBU',
 'CIDADE OCIDENTAL',
 'MARACANÃ',
 'ALTANEIRA',
 'MAQUINÉ',
 'SÃO ROQUE',
 'NOVA SANTA BÁRBARA',
 'PIRANGA',
 'MADALENA',
 'BURITINÓPOLIS',
 'PORTEIRINHA',
 'SANTA MARIA DE JETIBÁ',
 'BARREIRAS',
 'DENISE',
 'AROAZES',
 'CAJAMAR',
 'DAMOLÂNDIA',
 "SANTA RITA D'OESTE",
 'CRAÍBAS',
 'CANDIOTA',
 'JATOBÁ',
 'FORTALEZA',
 'RONDON DO PARÁ',
 'NOVA FRIBURGO',
 'ITIRUÇU',
 'TIJUCAS DO SUL',
 'CANAPI',
 'MONTIVIDIU',
 'AMARAJI',
 'PETROLÂNDIA',
 'IGARAPAVA',
 'GROAÍRAS',
 'PESQUEIRA',
 'SANTA RITA DO ARAGUAIA',
 'MONTADAS',
 'LAGOA VERMELHA',
 'GUAÇUÍ',
 'IPUBI',
 'BANDEIRA',
 'DOMINGOS MARTINS',
 'ALVORADA DO GURGUÉIA',
 'BURITIS',
 'LOBATO',
 'RIO NOVO',
 'VOLTA REDONDA',
 'MOGI GUAÇU',
 'CAJAZEIRAS',
 'BREJO DA MADRE DE DEUS',
 'RIBAS DO RIO PARDO',
 'MARIANO MORO',
 'MALTA',
 'JOÃO DIAS',
 'LUÍS CORREIA',
 'VITÓRIA',
 'SANTO EXPEDITO DO SUL',
 'AMARANTE DO MARANHÃO',
 'SÃO MARTINHO',
 "HERVAL D'OESTE",
 'TAMBORIL DO PIAUÍ',
 'NINHEIRA',
 'MARECHAL FLORIANO',
 'SÃO GABRIEL DO OESTE',
 'SANTANA DO IPANEMA',
 'SANTO ANTÔNIO DO PINHAL',
 'SABINÓPOLIS',
 'ARAUÁ',
 'GURUPI',
 'SÃO BRÁS',
 'VARGEM ALEGRE',
 'MASSAPÊ',
 'SARANDI',
 'ANAPU',
 'GUANHÃES',
 'PIO XII',
 'BALNEÁRIO ARROIO DO SILVA',
 'ÂNGULO',
 'APIACÁS',
 'VALINHOS',
 'SÃO LOURENÇO DO SUL',
 'VÁRZEA GRANDE',
 'VARGINHA',
 'SÃO JOSÉ DA BOA VISTA',
 'SANDOVALINA',
 'CACHOEIRA DO ARARI',
 'ARVOREDO',
 'ESPÍRITO SANTO',
 'PONTE ALTA DO NORTE',
 'OURO VERDE DE MINAS',
 'CONCEIÇÃO DO RIO VERDE',
 'NOVA ESPERANÇA',
 'GARARU',
 'PAQUETÁ',
 'LAVRINHAS',
 'IRACEMA',
 'BREJO GRANDE',
 'BONINAL',
 'FERNANDES PINHEIRO',
 'IBIRAREMA',
 'CONFRESA',
 'SÃO JERÔNIMO',
 'SONORA',
 'SAPUCAIA DO SUL',
 'CAXINGÓ',
 'IGUARAÇU',
 'PINDORAMA DO TOCANTINS',
 'PORTO UNIÃO',
 'VIDAL RAMOS',
 'SERRANÓPOLIS DO IGUAÇU',
 'DIVISA NOVA',
 'LINHARES',
 'VENTUROSA',
 'CAMPINAS DO PIAUÍ',
 'MAIRINQUE',
 'TERESINA',
 'ANHEMBI',
 'ESTIVA GERBI',
 'NOVA BOA VISTA',
 'ROSÁRIO DO CATETE',
 'ITAPURANGA',
 'NOVA ALIANÇA DO IVAÍ',
 'SÃO BENEDITO',
 'PARAÍSO DAS ÁGUAS',
 'MUCURICI',
 'MANARI',
 'ITABORAÍ',
 'GRAVATÁ',
 'PRESIDENTE OLEGÁRIO',
 'BREJO ALEGRE',
 'ROSÁRIO OESTE',
 'SÃO JOSÉ DO OURO',
 'GUARAQUEÇABA',
 'MESQUITA',
 'CAPARAÓ',
 'GASPAR',
 'RIBEIRÃO CLARO',
 'SANTA MARIA DA BOA VISTA',
 'TORRE DE PEDRA',
 'COLORADO',
 'VARGEM ALTA',
 'CIPÓ',
 'CAPISTRANO',
 'COMENDADOR LEVY GASPARIAN',
 'PARACURU',
 'SALDANHA MARINHO',
 'NILO PEÇANHA',
 'PASSAGEM',
 'GLÓRIA DO GOITÁ',
 'SANTO AMARO DA IMPERATRIZ',
 'ABAETÉ',
 'PARAGUAÇU',
 'ITUBERÁ',
 'FRANCISCO ALVES',
 'ARACRUZ',
 'FARIAS BRITO',
 'JATAÍ',
 'RONDINHA',
 'JUAREZ TÁVORA',
 'SANTA CRUZ',
 'PONTAL DO PARANÁ',
 'BACURI',
 'ITAMONTE',
 'OURO VERDE',
 'RIO BRANCO DO SUL',
 'JOSÉ GONÇALVES DE MINAS',
 'RIO QUENTE',
 'XIQUE-XIQUE',
 'SALVADOR',
 'CANARANA',
 'ITAMARAJU',
 'MIRACEMA',
 ...]

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos,Código da Emenda_1
348,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,SÃO PAULO - SP,3550308,SÃO PAULO,3500000,...,PROMOCAO DOS DIREITOS HUMANOS,0,PROMOCAO E DEFESA DOS DIREITOS HUMANOS - DESPE...,1499997.98,0.0,0.0,0.00,0.0,1499997.98,Sem informação
948,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,SÃO PAULO - SP,3550308,SÃO PAULO,3500000,...,APOIO A MANUTENCAO DE UNIDADES DE SAUDE,0,APOIO A MANUTENCAO DE UNIDADES DE SAUDE - DESP...,100000.00,0.0,0.0,0.00,0.0,100000.00,Sem informação
1239,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,RIO DE JANEIRO - RJ,3304557,RIO DE JANEIRO,3300000,...,PROMOCAO E FOMENTO A CULTURA BRASILEIRA,0,PROMOCAO E FOMENTO A CULTURA BRASILEIRA - DESP...,1100900.41,150000.0,150000.0,0.00,60360.0,890540.41,Sem informação
1397,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,SÃO PAULO - SP,3550308,SÃO PAULO,3500000,...,APOIO A INFRAESTRUTURA PARA A EDUCACAO BASICA,0,INFRAESTRUTURA PARA A EDUCACAO BASICA - DESPES...,1249500.00,0.0,0.0,0.00,0.0,1249500.00,Sem informação
1437,Sem informação,2014,Emenda Individual - Transferências com Finalid...,NaN,None,S/I,SÃO PAULO - SP,3550308,SÃO PAULO,3500000,...,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,6468350.24,0.0,0.0,1190060.78,3092000.0,2186289.46,Sem informação

sp:343
rj:464

Rio de Janeiro tem mais emendas, 464, que São Paulo, 343

## 4) Na coluna `Código da Emenda`, substitua todos os valores `"Sem informação"` por `"Não disponível"`. Mostre a contagem de valores únicos da coluna antes e depois da substituição.

In [124]:
dados = dados.replace({'Código da Emenda' : {'Sem informação': 'Não disponível'}})
print(dados['Código da Emenda'].nunique())
print((dados['Código da Emenda'] == 'Não disponível').value_counts())

70731
Código da Emenda
False    70851
True     17808
Name: count, dtype: int64

## 5) Na coluna `Nome Função`, transforme todos os valores para que fiquem em letras maiúsculas. Confirme a alteração mostrando os valores únicos da coluna.

In [125]:
dados['Nome Função'] = dados['Nome Função'].str.upper()
dados['Nome Função'].unique().tolist()

['URBANISMO',
 'COMÉRCIO E SERVIÇOS',
 'SAÚDE',
 'EDUCAÇÃO',
 'AGRICULTURA',
 'ASSISTÊNCIA SOCIAL',
 'DESPORTO E LAZER',
 'DEFESA NACIONAL',
 'SANEAMENTO',
 'DIREITOS DA CIDADANIA',
 'GESTÃO AMBIENTAL',
 'CULTURA',
 'CIÊNCIA E TECNOLOGIA',
 'SEGURANÇA PÚBLICA',
 'ORGANIZAÇÃO AGRÁRIA',
 'COMUNICAÇÕES',
 'ADMINISTRAÇÃO',
 'HABITAÇÃO',
 'INDÚSTRIA',
 'TRABALHO',
 'MÚLTIPLO',
 'TRANSPORTE',
 'PREVIDÊNCIA SOCIAL',
 'ENCARGOS ESPECIAIS',
 'RELAÇÕES EXTERIORES',
 'ENERGIA',
 'ESSENCIAL À JUSTIÇA']

## 6) Verifique quantas linhas duplicadas existem no dataset. Em seguida, remova as duplicatas e mostre quantas linhas sobraram.

In [126]:
print(dados.duplicated().sum())
dados_uniq = dados.drop_duplicates()
print(dados_uniq.duplicated().sum())

63
0

## 7) Remova duplicatas considerando apenas as colunas `Código da Emenda` e `Município`. Quantas linhas sobraram? O resultado é diferente de quando removemos duplicatas do DataFrame inteiro?

In [127]:
print(dados.duplicated(subset=['Código da Emenda', 'Município']).sum())
dados_uniq_municipio = dados.drop_duplicates(subset=['Código da Emenda', 'Município'])
len(dados_uniq_municipio)

12915

75744

Sobraram 75744 linhas, foram removidas 12915 enquanto foram removidas 63 duplicadas do DataFrame todo

## 8) Identifique quais colunas possuem valores nulos e quantos nulos cada uma tem. Em seguida, responda: qual é a coluna que possui maior número de valores nulos e quantos são?

In [128]:
dados.isnull().sum()

Código da Emenda                          0
Ano da Emenda                             0
Tipo de Emenda                            0
Código do Autor da Emenda             15961
Nome do Autor da Emenda               15961
Número da emenda                          0
Localidade de aplicação do recurso        0
Código Município IBGE                     0
Município                                 0
Código UF IBGE                            0
UF                                        0
Região                                    0
Código Função                             0
Nome Função                               0
Código Subfunção                          0
Nome Subfunção                            0
Código Programa                           0
Nome Programa                             0
Código Ação                               0
Nome Ação                                 0
Código Plano Orçamentário                 0
Nome Plano Orçamentário                   0
Valor Empenhado                           0
Valor Liquidado                           0
Valor Pago                                0
Valor Restos A Pagar Inscritos            0
Valor Restos A Pagar Cancelados           0
Valor Restos A Pagar Pagos                0
Código da Emenda_1                        0
dtype: int64

O Código e o Nome do Autor da Emenda tem 15961 valores nulos sendo as unicas colunas com valores nulos

## 9) Preencha os valores nulos da coluna `codigo do autor` com **-1** e os valores nulos da coluna `nome do autor da emenda` com "desconhecido" e confirme que não restaram nulos nessa coluna.

In [129]:
dados['Código do Autor da Emenda'] = dados['Código do Autor da Emenda'].fillna(-1)
dados['Nome do Autor da Emenda'] = dados['Nome do Autor da Emenda'].fillna('Desconhecido')

dados.isnull().sum()

Código da Emenda                      0
Ano da Emenda                         0
Tipo de Emenda                        0
Código do Autor da Emenda             0
Nome do Autor da Emenda               0
Número da emenda                      0
Localidade de aplicação do recurso    0
Código Município IBGE                 0
Município                             0
Código UF IBGE                        0
UF                                    0
Região                                0
Código Função                         0
Nome Função                           0
Código Subfunção                      0
Nome Subfunção                        0
Código Programa                       0
Nome Programa                         0
Código Ação                           0
Nome Ação                             0
Código Plano Orçamentário             0
Nome Plano Orçamentário               0
Valor Empenhado                       0
Valor Liquidado                       0
Valor Pago                            0
Valor Restos A Pagar Inscritos        0
Valor Restos A Pagar Cancelados       0
Valor Restos A Pagar Pagos            0
Código da Emenda_1                    0
dtype: int64

## 10) Verifique o tipo da coluna `Ano da Emenda`. Converta-a para **string** (`str`). Mostre o tipo antes e depois da conversão.

In [130]:
print(dados['Ano da Emenda'].dtypes)
dados_ano_str = dados['Ano da Emenda'].astype(str)
print(dados_ano_str.dtypes)

int64
object

## 11) Converta a coluna `Valor Empenhado` para o tipo **float** (caso ainda não seja). Mostre o tipo após a conversão.

In [131]:
print(dados['Valor Empenhado'].dtypes)

float64

## 12) Calcule o **total** de `Valor Pago` por **Região**. Quais são as duas regiões que mais receberam recursos?

In [132]:
total_por_regiao = dados.groupby("Região")["Valor Pago"].sum().sort_values()

display(total_por_regiao)

Região
Exterior        2.572317e+07
Nacional        7.886148e+09
Centro-Oeste    1.037094e+10
Sul             1.648893e+10
Norte           2.035103e+10
Múltiplo        3.010563e+10
Sudeste         3.427210e+10
Nordeste        4.644963e+10
Name: Valor Pago, dtype: float64

Sudeste e Nordeste foram as regiões que mais receberam recursos com mais de 80 bilhões juntos

## 13) Calcule a **quantidade** de emendas por **Nome Função**. Mostre as 5 funções com mais emendas.

In [133]:
dados['Nome Função'].value_counts().head()

Nome Função
SAÚDE                 37068
URBANISMO              8663
EDUCAÇÃO               8108
AGRICULTURA            4940
ENCARGOS ESPECIAIS     4610
Name: count, dtype: int64

## 14) Crie uma nova coluna chamada `Saldo a Pagar`. Ela deve ser o resultado da subtração entre a coluna `Valor Empenhado` e a coluna `Valor Pago`. Mostre as 5 primeiras linhas apenas com essas três colunas.

In [134]:
dados['Saldo a Pagar'] = dados['Valor Empenhado'] - dados['Valor Pago']
dados[['Saldo a Pagar', 'Valor Pago', 'Valor Empenhado']].head()

   Saldo a Pagar  Valor Pago  Valor Empenhado
0      700000.00         0.0        700000.00
1      487500.00         0.0        487500.00
2      100000.00         0.0        100000.00
3      243750.00         0.0        243750.00
4     1658333.94         0.0       1658333.94

## 15) Elimine a(s) coluna(s) do dataframe que eestá totalmente vazia.

## 16) Para finalizar, salve o DataFrame transformado em um arquivo no formato JSON.